// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TgBotVetMedIst_uchun;

#nullable disable

namespace TgBot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TgBot.Models.BotUserData", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Api_Access_Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Api_Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Api_FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Api_Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Api_HemisId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Api_LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Api_Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("UserLast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserNameSearch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserTelNum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BotUserDB");
                });

            modelBuilder.Entity("TgBot.Models.DownloadedFileAdressToTg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("fileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("fileTgAdressId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FileTgAdressDb");
                });
#pragma warning restore 612, 618
        }
    }
}
